# Generated by Django 4.0.6 on 2022-07-11 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('users_name', models.CharField(blank=True, max_length=200, null=True)),
                ('users_email', models.CharField(blank=True, max_length=200, null=True)),
                ('users_avatar_url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
